version: "2"

services:
  tensorflow:
    image: tensorflow/tensorflow
    #volumes:
      # Se colocar os meus notebooks ele perde do getting started
      #- ./notebooks:/notebooks/
    ports:
      - "8888:8888"